# Generated by Django 5.2.8 on 2025-11-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('EARNED', 'Earned Leave')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='applied_at',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
