# Generated by Django 5.2.8 on 2025-11-14 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold')], max_length=20)),
                ('department_id', models.IntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client_name', models.CharField(max_length=200)),
                ('technology_used', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProjectMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('responsibilities', models.TextField()),
                ('assigned_date', models.DateField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('allocation_percentage', models.PositiveIntegerField(default=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project')),
            ],
        ),
    ]
