# Generated by Django 5.2.8 on 2025-11-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('HR_ADMIN', 'HR Admin'), ('EMPLOYEE', 'Employee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(max_length=10),
        ),
    ]
