# Generated by Django 5.2.8 on 2025-11-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_holiday_regularizationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_overtime_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
