# Generated by Django 5.2.8 on 2025-11-13 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_is_overtime_manual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='regularizationrequest',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='regularizationrequest',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='regularizationrequest',
            name='requested_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='regularizationrequest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='regularizationrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Early Leave', 'Early Leave'), ('Holiday', 'Holiday'), ('Absent', 'Absent')], max_length=20),
        ),
    ]
